### ISSUE TITLE
when bf4 server have a password, how i join it

### ISSUE THREAD

**Issue by Frank997** [GVNCoder/34HLauncher#26]
my server has a game password, but when i join, no password input dialog out, it just direct join game with no password and got join failed.

**Comment by GVNCoder** [comment]
Thanks for your feedback.
I'll investigate is it possible to implement passworded servers on ZLOEmu project.

**Comment by GVNCoder** [comment]
> my server has a game password, but when i join, no password input dialog out, it just direct join game with no password and got join failed.

Thanks for your feedback.
I'll investigate is it possible to implement passworded servers on ZLOEmu project.

**Comment by Frank997** [comment]
> > my server has a game password, but when i join, no password input dialog out, it just direct join game with no password and got join failed.
> 
> Thanks for your feedback. I'll investigate is it possible to implement passworded servers on ZLOEmu project.

expect it, thx for your work.

**Comment by GVNCoder** [comment]
@Frank997 please, provide me your server id here

**Comment by Frank997** [comment]
hi, now you can see my server in zloemu server list.
my server is a bf4 server,  the name is "A server with password", the password is "123".

**Comment by Frank997** [comment]
> @Frank997 please, provide me your server id here

@GVNCoder my server is a bf4 server, the name is "A server with password", the join password is "123".

now you can see my server on zloemu bf4 server list, i upped it just now.

**Comment by GVNCoder** [comment]
Currently I already implemented private servers logic in Zlo4NET API and doing some testing with launcher.

**Comment by Frank997** [comment]
> Currently I already implemented private servers logic in Zlo4NET API and doing some testing with launcher.
> ![image](https://user-images.githubusercontent.com/37244024/152641552-d0f86aa1-2681-4f80-94df-33dfb616145a.png)
> 

gj, thx your work!

**Comment by GVNCoder** [comment]
@Frank997 Please, restart your ZServer and server

**Comment by Frank997** [comment]
ok

**Comment by Frank997** [comment]
> @Frank997 Please, restart your ZServer and game server

i already restarted

**Comment by GVNCoder** [comment]
Corresponding Zlo4NET API [Release v0.5.5.0](https://github.com/GVNCoder/Zlo4NET/releases/tag/v0.5.5.0-pre-alpha)

**Comment by GVNCoder** [comment]
Now, I'm working on launcher testing

**Comment by Frank997** [comment]
> Now, I'm working on launcher testing

thx your work, i will try new version

**Comment by GVNCoder** [comment]
#27 will be included in the next update v0.125.11.0

**Comment by Frank997** [comment]
> #27 will be included in the next update v0.125.11.0

ok, thx.
btw my server now can stop? if you are need not more testing, i will stop it, because most time i only start it when i play with friend.
